folder_groups:
  documents:
  - D:/test_sync/docs/work
  - D:/test_sync/docs/backup
  - D:/test_sync/docs/archive
  media:
  - D:/test_sync/media/photos
  - D:/test_sync/media/process
  - D:/test_sync/media/backup
  source_code:
  - D:/test_sync/code/dev
  - D:/test_sync/code/test
  - D:/test_sync/code/backup
  自立:
  - D:/test/common1
  - D:/test/common2
  - D:/test/common3
folders:
- D:/test_sync/folder1
- D:/test_sync/folder2
- D:/test_sync/folder3
